name: dart_coin_rpc
description: A simple RPC client for bitcoin-like coins created in dart.
version: 2.1.7
homepage: https://github.com/peercoin/dart_coin_rpc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.4